#-------------------------------------------------------------------------
# TITLE: 
#    pkgIndex.tcl
#
# PROJECT:
#    tcl-markdown: Markdown Processor
#
# DESCRIPTION:
#    tcl-markdown quillinfo(n): pkgIndex file
#
#    Generated by Quill
#-------------------------------------------------------------------------

package ifneeded quillinfo 1.0 [list source [file join $dir pkgModules.tcl]]
