#-------------------------------------------------------------------------
# TITLE: 
#    quillinfo.tcl
#
# PROJECT:
#    tcl-markdown: Markdown Processor
#
# DESCRIPTION:
#    Project Metadata
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Exported Commands

namespace eval ::quillinfo {
    variable meta
    array set meta {gui-md2html 0 url http://my.home.page description {Markdown Processor} provides markdown distpat-install {
    %libs
    docs/*.html
    docs/man*/*.html
    README.md
    LICENSE
} homepage http://home.page.url requires Tcl exetype-md2html kit local-Tcl 0 apps md2html version 0.0.1 version-Tcl 8.6.3 project tcl-markdown dists install}

    namespace export \
        project      \
        description  \
        version      \
        homepage     \
        isgui

    namespace ensemble create
}

#-------------------------------------------------------------------------
# Commands

# project
#
# Returns the project name.

proc ::quillinfo::project {} {
    variable meta
    return $meta(project)
}

# description 
#
# Returns the project's description.

proc ::quillinfo::description {} {
    variable meta
    return $meta(description)
}

# version 
#
# Returns the project version number.

proc ::quillinfo::version {} {
    variable meta
    return $meta(version)
}

# homepage 
#
# Returns the project home page URL.

proc ::quillinfo::homepage {} {
    variable meta
    return $meta(homepage)
}

# isgui app
#
# app   - An app name for this project.
#
# Returns true if the app is a GUI and false otherwise.

proc ::quillinfo::isgui {app} {
    variable meta

    if {[info exists meta(gui-$app)]} {
        return $meta(gui-$app)
    } else {
        return 0
    }
}
