#-------------------------------------------------------------------------
# TITLE: 
#    pkgModules.tcl
#
# PROJECT:
#    tcl-markdown: Your project description
#
# DESCRIPTION:
#    app_md2html(n): Package Loader
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Provide Package

# -quill-provide-begin DO NOT EDIT BY HAND
package provide app_md2html 0.0.1
# -quill-provide-end

#-------------------------------------------------------------------------
# Require Packages

# -quill-require-begin INSERT PACKAGE REQUIRES HERE
package require markdown 0.0.1
# -quill-require-end

#-------------------------------------------------------------------------
# Get the library directory

namespace eval ::app_md2html:: {
    variable library [file dirname [info script]]
}

source [file join $::app_md2html::library main.tcl     ]
source [file join $::app_md2html::library fileutil.tcl ]
