#-------------------------------------------------------------------------
# TITLE: 
#    pkgIndex.tcl
#
# PROJECT:
#    tcl-markdown: Your project description
#
# DESCRIPTION:
#    markdown(n): pkgIndex file
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

# -quill-ifneeded-begin DO NOT EDIT BY HAND
package ifneeded markdown 0.0.1 [list source [file join $dir pkgModules.tcl]]
# -quill-ifneeded-end
