#-------------------------------------------------------------------------
# TITLE: 
#    pkgModules.tcl
#
# PROJECT:
#    tcl-markdown: Your project description
#
# DESCRIPTION:
#    markdown(n): Package Loader
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Provide Package

# -quill-provide-begin DO NOT EDIT BY HAND
package provide markdown 0.0.1
# -quill-provide-end

#-------------------------------------------------------------------------
# Require Packages

# -quill-require-begin INSERT PACKAGE REQUIRES HERE
# -quill-require-end

#-------------------------------------------------------------------------
# Get the library directory

namespace eval ::markdown:: {
    variable library [file dirname [info script]]
}

source [file join $::markdown::library markdown.tcl]
